resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      shipping:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 2s
      shipping:
        maxAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      inventory:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
      shipping:
        limitForPeriod: 5
        limitRefreshPeriod: 10s

  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s
      shipping:
        timeoutDuration: 3s
